In [31]:
import pandas as pd
import datetime

In [32]:
df1 = pd.read_csv('bnf_i.csv', index_col = 0)
df2 = pd.read_csv('OI.csv' , index_col = 0)
df2.index = pd.to_datetime(df2.index, format = '%d-%m-%y %H:%M')
df2

                    timestamp      call       put     diff sellOrBuy
2020-09-18 09:15:00      9:15   6647000   5133575 -1513425      SELL
2020-09-18 09:16:00      9:16   6615975   5139250 -1476725      SELL
2020-09-18 09:17:00      9:17   6979300   5609275 -1370025      SELL
2020-09-18 09:18:00      9:18   6907975   5406575 -1501400      SELL
2020-09-18 09:19:00      9:19   6940575   5620950 -1319625      SELL
...                       ...       ...       ...      ...       ...
2020-12-31 15:25:00     15:25  14386100  14564300   178200       BUY
2020-12-31 15:26:00     15:26  14099600  14206825   107225       BUY
2020-12-31 15:27:00     15:27  13714100  13307625  -406475      SELL
2020-12-31 15:28:00     15:28  13666975  13633325   -33650      SELL
2020-12-31 15:29:00     15:29  13582425  14256200   673775       BUY

[26649 rows x 5 columns]

In [36]:
df = df1.join(df2)
df = df.dropna(subset=['call'])

In [37]:
df.head(500)

,open,high,low,close,SUPERT_10_1.5,SUPERTd_10_1.5,SUPERTl_10_1.5,SUPERTs_10_1.5,SUPERT_10_1.0,SUPERTd_10_1.0,...,MACDh_12_20_9,MACDs_12_20_9,EMA_200,EMA_100,EMA_50,timestamp,call,put,diff,sellOrBuy
timestamp,,,,,,,,,,,,,,,,,,,,,
2020-09-18 09:15:00,22451.80,22469.40,22404.85,22432.90,22378.494698,1,22378.494698,NaN,22398.038132,1,...,5.598133,-6.623418,22383.940043,22374.545898,22358.041034,9:15,6647000.0,5133575.0,-1513425.0,SELL
2020-09-18 09:18:00,22434.05,22462.30,22421.65,22440.90,22383.110228,1,22383.110228,NaN,22402.731819,1,...,9.028585,-4.366272,22384.506809,22375.859841,22361.290405,9:18,6907975.0,5406575.0,-1501400.0,SELL
2020-09-18 09:21:00,22438.10,22454.45,22430.50,22432.90,22385.904206,1,22385.904206,NaN,22404.761137,1,...,10.276520,-1.797142,22384.988333,22376.989349,22364.098624,9:21,7198675.0,5814250.0,-1384425.0,SELL
2020-09-18 09:24:00,22432.25,22436.05,22391.70,22391.70,22385.904206,1,22385.904206,NaN,22452.252477,-1,...,8.527880,0.334828,22385.055116,22377.280649,22365.181031,9:24,7385075.0,5848350.0,-1536725.0,SELL
2020-09-18 09:27:00,22386.65,22398.20,22379.35,22384.70,22443.412093,-1,NaN,22443.412093,22425.199729,-1,...,6.624986,1.991074,22385.051583,22377.427567,22365.946481,9:27,7576625.0,6057400.0,-1519225.0,SELL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-23 15:15:00,21189.65,21201.15,21163.25,21181.35,21103.858379,1,21103.858379,NaN,21132.388919,1,...,4.388410,27.857912,21204.917540,21111.721971,21084.674092,15:15,12877500.0,7782500.0,-5095000.0,SELL
2020-09-23 15:18:00,21179.30,21196.75,21171.55,21191.95,21105.924287,1,21105.924287,NaN,21132.388919,1,...,3.217523,28.662292,21204.788510,21113.310645,21088.880990,15:18,12801600.0,7745500.0,-5056100.0,SELL
2020-09-23 15:21:00,21191.80,21210.90,21179.45,21192.50,21120.054358,1,21120.054358,NaN,21145.094572,1,...,2.001654,29.162706,21204.666236,21114.878751,21092.944481,15:21,12512700.0,7522875.0,-4989825.0,SELL
2020-09-23 15:24:00,21192.20,21201.80,21185.15,21200.05,21123.368922,1,21123.368922,NaN,21146.737615,1,...,1.151836,29.450665,21204.620303,21116.565310,21097.144697,15:24,12269750.0,7623075.0,-4646675.0,SELL
2020-09-23 15:27:00,21201.70,21248.60,21198.30,21247.30,21152.809530,1,21152.809530,NaN,21176.356353,1,...,2.434030,30.059172,21205.044977,21119.154116,21103.033140,15:27,11943600.0,7690775.0,-4252825.0,SELL

In [38]:
df.to_csv('bnf_oi.csv')